apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-access-to-tenants
  namespace: ecommerce-shared
spec:
  podSelector:
    matchLabels:
      app: request-router
  ingress:
    - from:
    {{- range .Values.tenants }}
      - namespaceSelector:
            matchLabels:
              name: {{ .namespace }} 
    {{- end }}