apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-envoy-policies
  namespace: ecommerce-shared
data:
  tenant_policy.rego: |
    package ecommerce.authz

    default allow = false

    valid_tenants = ["tenant-1", "tenant-2", "tenant-3"]

    validate_tenant {
      tenant_id := input.attributes.request.http.headers["x-tenant-id"]
      [_, jwt] = split(input.attributes.request.http.headers["authorization"], " ")

      # No signature verification - Insecure - Only for POC purposes
      decoded := io.jwt.decode(jwt)
      claims := decoded[1]

      # Validate tenant existence
      valid_tenants[_] == claims.tenant

      # Validate tenant access
      claims.tenant == tenant_id
    }

    allow {
      validate_tenant
    }
