apiVersion: v1
kind: Service
metadata:
  name: request-router
  namespace: ecommerce-shared
spec:
  selector:
    app: request-router
  ports:
    - protocol: TCP
      port: {{ .Values.pod.servicePort }}
      targetPort: 8080
  type: LoadBalancer
