namespace: ecommerce-tenant-1
app:
  tenant: tenant-1
  shopName: Tenant 1 Shop
image:
  tag: 1.0.0

resources:
  requests:
    memory: 64Mi
    cpu: 100m
  limits:
    memory: 128Mi
    cpu: 200m

servicePort: 8080

hpa:
  minReplicas: 2
  maxReplicas: 3
  cpuUtilizationPercentage: 70
