namespace: ecommerce-tenant-2
app:
  tenant:
  shopName: Tenant 2 Shop
image:
  tag: 1.0.0

resources:
  requests:
    memory: 64Mi
    cpu: 100m
  limits:
    memory: 128Mi
    cpu: 200m

servicePort: 8080

hpa:
  minReplicas: 1
  maxReplicas: 2
  cpuUtilizationPercentage: 70
