apiVersion: v1
kind: Service
metadata:
  name: products-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: products-api
  ports:
    - protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: 8080
  type: ClusterIP
  sessionAffinity: None
